---
title: "Lab 6 Warmup"
output: html_document
date: "2024-01-30"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```
```{r}
library(tidyverse)
```

###1. Load bison data
```{r}
bison <- read_csv("data/bison.csv")
```
###2. Dimensions and structure of the data
```{r}
dim(bison)
```
```{r}
str(bison)
```
###. Only interested in code, sex, weight, year of birth
```{r}
names(bison)
```
```{r}
selectivebison <- bison %>% 
  select(animal_code, animal_sex, animal_weight, animal_yob)
```
###. pull out the animals born between 1980-1990
```{r}
filtered_bison <- selectivebison %>% 
  filter(between(animal_yob, 1980,1990))
```

###5. How many male and female bison are represented between 1980-1990
```{r}
summary(filter(filtered_bison, animal_sex == "F"))
```
### Or 
```{r}
male_bison <-selectivebison %>% 
  filter(between(animal_yob, 1980,1990)) %>% 
  filter(animal_sex=="M")

female_bison<-selectivebison %>% 
  filter(between(animal_yob, 1980,1990)) %>% 
  filter(animal_sex=="F")


```


```{r}
summary(filter(filtered_bison, animal_sex == "M"))
```
### 6. Males or females larger on average between 1980 and 1990
```{r}
male_bison <- filter(filtered_bison, animal_sex == "M")
```
```{r}
female_bison <- filter(filtered_bison, animal_sex == "F")
```
```{r}
mean(male_bison$animal_weight)
```

```{r}
mean(female_bison$animal_weight)
```
Males are larger on average!
